// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RPGHexplorer.Api.DataBases;

namespace RPGHexplorer.Api.Migrations
{
    [DbContext(typeof(MapDbContext))]
    [Migration("20190206161305_InitalCreate")]
    partial class InitalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RPGHexplorer.Common.TileMaps.Map", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("RPGHexplorer.Common.TileMaps.Tile", b =>
                {
                    b.Property<string>("MapId");

                    b.Property<string>("Id");

                    b.HasKey("MapId", "Id");

                    b.ToTable("Tiles");
                });
#pragma warning restore 612, 618
        }
    }
}
